### ISSUE TITLE
Repository structure for v1.3.0 is not compliant

### ISSUE THREAD

**Issue by riemers** [jbouwh/omnikdatalogger.origin#7]
I get what the subject says "Repostitory structure for v1.3.0 is not compliant" when adding the repo into HACS. 

Think it might need a bump, or i am totally doing something wrong :)

**Comment by jbouwh** [comment]
Ok, i will have a look. Since omnikportal is down, the code will need an update. I will fix HACS as well.

**Comment by jbouwh** [comment]
Please let me know if you still experince issues with the new release. https://github.com/jbouwh/omnikdatalogger/releases/tag/v1.4.0. I installed the update using HACS within a problem.

**Comment by jbouwh** [comment]
Test uninstalling and reinstalling do not give any errors with the latest version. Closing issue

**Comment by riemers** [comment]
![image](https://user-images.githubusercontent.com/682041/118726555-c8667c00-b831-11eb-81ec-1dfb8b9aa09f.png)
This is normally how i add it though. In your readme it says, search for omnik, it only shows me 1 by default which is not yours.

**Comment by jbouwh** [comment]
Add it from automations, no url is needed. https://github.com/jbouwh/omnikdatalogger/wiki/Install-using-HACS-(Home-Assistant-Community-Store)#install-omnik-datalogger-using-hacs

**Comment by riemers** [comment]
Either i am blind or not getting it, inside HACS there is nothing called "Automations" and inside HA itself there is "Automations" but if i search there it finds nothing.

![image](https://user-images.githubusercontent.com/682041/118727909-d61d0100-b833-11eb-803d-8feceea062c4.png)

**Comment by jbouwh** [comment]
> ![image](https://user-images.githubusercontent.com/682041/118726555-c8667c00-b831-11eb-81ec-1dfb8b9aa09f.png)
> This is normally how i add it though. In your readme it says, search for omnik, it only shows me 1 by default which is not yours.

Omnikdatalogger is not an integration but an automation. You will need to install the AppDaemon addon aswell when you want to user HACS.

**Comment by riemers** [comment]
Owww, i need appdeamon. Now a lightbulb appears. With HACS i am so used to add repo, install and all is presto ;)

**Comment by jbouwh** [comment]
At the main page Automatisering, than hit the big +

Erik-jan Riemers ***@***.***> schreef op 18 mei 2021 23:50:55 CEST:
>Either i am blind or not getting it, inside HACS there is nothing
>called "Automations" and inside HA itself there is "Automations" but if
>i search there it finds nothing.
>
>![image](https://user-images.githubusercontent.com/682041/118727909-d61d0100-b833-11eb-803d-8feceea062c4.png)
>
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/jbouwh/omnikdatalogger/issues/7#issuecomment-843589804

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jbouwh** [comment]
![Screenshot_20210518-235501_Home Assistant](https://user-images.githubusercontent.com/7188918/118728483-8854c880-b834-11eb-9b20-d8655c43af21.jpg)

**Comment by jbouwh** [comment]
![Screenshot_20210518-235610_Home Assistant](https://user-images.githubusercontent.com/7188918/118728554-a91d1e00-b834-11eb-84b4-dd5391d05565.jpg)

**Comment by jbouwh** [comment]
Yep, you can jnstall appdaemon addon using the official addon store.

Erik-jan Riemers ***@***.***> schreef op 18 mei 2021 23:52:45 CEST:
>Owww, i need appdeamon. Now a lightbulb appears. With HACS i am so used
>to add repo, install and all is presto ;)
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/jbouwh/omnikdatalogger/issues/7#issuecomment-843590660

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by riemers** [comment]
Yeah sorry about that, it only shows automation if you have appdeamon. I was unaware. My bad.
